.\"             -*-Nroff-*-
.\"
.TH "in" 1 "3 Feb 2021" "" ""
.SH NAME
gionice \- execute a command in an IO friendly way
.sp
THIS MAN PAGE IS A WORK IN PROGRESS
.SH SYNOPSIS
.B gionice
directory command
.sp
.SH DESCRIPTION
Run the given command with an IO-friendly priority, or with a custom set priority.
See --help for more info.
.sp
.SH VERSION
1.0.0
.SH BUGS
No known bugs so far. Issues can be reported at: https://github.com/xyproto/ionice/issues
.SH AUTHOR
.B in
was written by Alexander F. Rødseth <xyproto@archlinux.org>
